hmcts/dg-docassembly-api

src/aat/java/uk/gov/hmcts/reform/dg/docassembly/functional/TemplateRenditionResourceTests.java, src/main/java/uk/gov/hmcts/reform/dg/docassembly/dto/RenditionOutputType.java
https://tools.hmcts.net/jira/browse/EM-1287
```
[ ] Yes
[ X] No
```
=> extended output type list

Dockerfile, build.gradle
EM-1288
```
[ ] Yes
[x] No
```
=> cnp dependencies

infrastructure/aat.tfvars
=> [PREVIEW] changed base url for idam to use sidam

README.md, docker-compose-demo.yml, docker-compose.yml, src/main/java/uk/gov/hmcts/reform/dg/docassembly/service/TemplateRenditionService.java, src/test/java/uk/gov/hmcts/reform/dg/docassembly/service/TemplateRenditionServiceTest.java
https://tools.hmcts.net/jira/browse/EM-1389
Stop NPE being thrown when formPayload is not set in the template-rendition call  
```
[ ] Yes
[x] No
```
=> [PREVIEW] guard against NPE when formPayload is not set

charts/dg-docassembly/Chart.yaml, charts/dg-docassembly/values.yaml
=> rename to values.yaml

Jenkinsfile_CNP, src/aat/java/uk/gov/hmcts/reform/dg/docassembly/functional/FormDefinitionResourceTests.java, src/aat/java/uk/gov/hmcts/reform/dg/docassembly/testutil/IdamHelper.java
stop deploying to prod
```
[ ] Yes
[ ] No
```
=> stop deploying to prod

infrastructure/variables.tf
Adding CMC as an authorised service.
```
[ ] Yes
[x] No
```
=> CMC: add claim-store service

build.gradle, config/owasp/dependency-check-suppressions.xml, pacts/docassembly_api-idam_api.json, src/contractTest/java/uk/gov/hmcts/reform/dg/docassembly/IdamConsumerTest.java
=> sidam pact + oawsp dep update

Jenkinsfile_CNP
- allow deployments to prod
```
[ ] Yes
[X] No
```
=> allow deployment to prod

infrastructure/aat.tfvars
turn on form_definition_endpoint in aat
```
[ ] Yes
[X] No
```
=> turn on form_definition_endpoint in aat

charts/dg-docassembly/Chart.yaml, charts/dg-docassembly/requirements.yaml, config/owasp/dependency-check-suppressions.xml
=> EM-2132: Update Java version and bump Helm chart number

charts/dg-docassembly/Chart.yaml, charts/dg-docassembly/requirements.yaml, charts/dg-docassembly/values.aat.template.yaml, charts/dg-docassembly/values.preview.template.yaml, charts/dg-docassembly/values.yaml
https://tools.hmcts.net/jira/browse/EM-2258
=> Removed alias related lines

charts/dg-docassembly/Chart.yaml, charts/dg-docassembly/values.yaml
https://tools.hmcts.net/jira/browse/EM-2301
=> Updated the respective URL's

charts/dg-docassembly/Chart.yaml
=> add api version and bump chart

config/owasp/dependency-check-suppressions.xml
=> Suppressed vulnerabilities

Jenkinsfile_CNP, charts/dg-docassembly/values.preview.template.yaml, config/owasp/dependency-check-suppressions.xml
=> remove dockerbuild and aadID

infrastructure/main.tf
=> remove app comment secrets add RG

infrastructure/main.tf
=> uncomment secrets

infrastructure/main.tf
=> recomment secrets

infrastructure/main.tf
=> uncomment secrets again

charts/dg-docassembly/Chart.yaml, charts/dg-docassembly/requirements.yaml, config/owasp/dependency-check-suppressions.xml
=> update java chart to 16

README.md
https://tools.hmcts.net/jira/browse/EM-1873
Update readme with instructions to run idam script and fix functionals locally
```
[ ] Yes
[x] No
```
=> EM-1873-2: Update readme with instructions to install jq

Jenkinsfile_CNP, charts/dg-docassembly/Chart.yaml, charts/dg-docassembly/values.yaml, src/main/java/uk/gov/hmcts/reform/dg/docassembly/config/security/SecurityConfiguration.java
=> Removed the issuer validation

Jenkinsfile_CNP, build.gradle, config/owasp/dependency-check-suppressions.xml, pacts/docassembly_api-idam_api.json, src/contractTest/java/uk/gov/hmcts/reform/dg/docassembly/IdamConsumerTest.java
https://tools.hmcts.net/jira/browse/EM-2879
Updated changes for Pact broker integration in pipeline
```
[ ] Yes
[ X ] No
```
=> Em 2880 integrate pact broker

README.md, bin/idam-authenticate.sh, bin/idam-client-setup.sh, bin/idam/idam-create-user.sh, bin/idam/idam-get-s2s-token.sh, bin/idam/idam-get-user-token.sh, bin/idam/idam.sh, bin/start-local-environment.sh
https://tools.hmcts.net/jira/browse/EM-2930
Updated Code to incorporate idam and local scripts run
Updated read me file
```
[ ] Yes
[ X ] No
```
=> EM-2930 scripts for idam and local running

Jenkinsfile_CNP, Jenkinsfile_parameterized, build.gradle, src/aat/java/uk/gov/hmcts/reform/dg/docassembly/functional/BaseTest.java
https://tools.hmcts.net/jira/browse/EM-2723
Code changes for Serenity integrations and single report generations
```
[ ] Yes
[ X ] No
```
=> EM-2723 Updated code to use Serenity Runner and generate single report

pacts/docassembly_api-idam_api.json, src/contractTest/java/uk/gov/hmcts/reform/dg/docassembly/IdamConsumerTest.java
https://tools.hmcts.net/jira/browse/EM-2880
Fix Pact request json request body generation
```
[ ] Yes
[ X ] No
```
=> EM-2880 Fix POST request body generation in pact json

Jenkinsfile_CNP, config/owasp/dependency-check-suppressions.xml
=> test for isha

Jenkinsfile_CNP, build.gradle
=> Updated pact contract call

Jenkinsfile_nightly
EM:3076 - Enable Nightly Build Pipeline
=> EM:3076 - Enable Nightly Build Pipeline

build.gradle, src/aat/java/uk/gov/hmcts/reform/dg/docassembly/smoke/SmokeTest.java, src/main/java/uk/gov/hmcts/reform/dg/docassembly/rest/WelcomeResource.java, src/test/java/uk/gov/hmcts/reform/dg/docassembly/rest/WelcomeResourceTest.java
https://tools.hmcts.net/jira/browse/EM-3119
=> Updated em-test-helper version

infrastructure/main.tf
=> Updated MI creation

infrastructure/main.tf
=> Fix the vault copy issue

config/owasp/dependency-check-suppressions.xml, infrastructure/main.tf
Updated cnp-module-key-vault branch
=> Updated cnp-module-key-vault branch

config/owasp/dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/EM-3274
=> Suppressed vulnerability

build.gradle
=> EM-3427 - EM-Dg-doc api: Upgrade serenity version

build.gradle
https://tools.hmcts.net/jira/browse/EM-3517
=> Resolved CVE-2021-21290

charts/dg-docassembly/Chart.yaml, charts/dg-docassembly/values.yaml
- update docmosis URL
```
[ ] Yes
[X] No
```
=> Update DOCMOSIS URL

build.gradle
N/A
Updated Sonarqube config
```
[ ] Yes
[X] No
```
=> Updated Sonarqube config

README.md, build.gradle, docker-compose-dependencies-simulator.yml, src/aat/resources/application.yml, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/EM-3598
```
[ ] Yes
[X] No
```
=> Em 3598 update to rse idam simulator

audit.json
=> EM-3619 -EM-dg-docassembly-api: suppress security scan errors

build.gradle
N/A
Fixed pact report generation
```
[ ] Yes
[X] No
```
=> Fixed pact report generation

src/main/java/uk/gov/hmcts/reform/dg/docassembly/info/BuildInfo.java
https://tools.hmcts.net/jira/browse/EM-3754
Fixed Resource leak
```
[ ] Yes
[X] No
```
=> Fixed Resource leak

docker-compose-demo.yml, docker-compose-dependencies-simulator.yml, docker-compose-dependencies.yml
https://tools.hmcts.net/jira/browse/EM-3803
Updated docker-compose-dependencies
```
[ ] Yes
[X] No
```
=> Updated docker-compose-dependencies

src/main/resources/application.yaml
=> whitelist xui to allow conversion of MS Office file types

Jenkinsfile_nightly, build.gradle, config/fortify-client.properties, src/test/resources/logback.xml
https://tools.hmcts.net/jira/browse/EM-3962
Added in fortify library
```
[ ] Yes
[X] No
```
=> Added in fortify library

build.gradle, src/main/java/uk/gov/hmcts/reform/dg/docassembly/Application.java, src/main/java/uk/gov/hmcts/reform/dg/docassembly/config/ServiceTokenGeneratorConfiguration.java, src/main/java/uk/gov/hmcts/reform/dg/docassembly/config/security/SecurityUtils.java, src/main/java/uk/gov/hmcts/reform/dg/docassembly/service/ServiceNameAspect.java, src/test/java/uk/gov/hmcts/reform/dg/docassembly/rest/FormDefinitionResourceTest.java, src/test/java/uk/gov/hmcts/reform/dg/docassembly/rest/TemplateRenditionResourceTest.java, src/test/java/uk/gov/hmcts/reform/dg/docassembly/service/ServiceNameAspectTest.java
https://tools.hmcts.net/jira/browse/EM-3971
Added in logging to capture consuming service name
```
[ ] Yes
[X] No
```
=> Added in logging to capture consuming service name

build.gradle, src/main/java/uk/gov/hmcts/reform/dg/docassembly/service/ServiceNameAspect.java
N/A
Resolved slow build issue
```
[ ] Yes
[X] No
```
=> Resolved slow build issue

charts/dg-docassembly/Chart.yaml
https://tools.hmcts.net/jira/browse/EM-3994
Updated Chart Java version
```
[ ] Yes
[X] No
```
=> Updated Chart Java version

build.gradle, config/owasp/dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/EM-4014
Suppressed medium vulnerability
```
[ ] Yes
[X] No
```
=> Suppressed medium vulnerability

build.gradle, src/aat/resources/application.yml
EM-4032
bump spring boot version  2.5.4
```
[ ] Yes
[x] No
```
=> EM-4032: bump spring boot version  2.5.4

config/owasp/dependency-check-suppressions.xml
EM-4063
fix dependency check issue
```
[ ] Yes
[x] No
```
=> EM-4063: fix dependency check issue

src/main/java/uk/gov/hmcts/reform/dg/docassembly/service/ServiceNameAspect.java, src/test/java/uk/gov/hmcts/reform/dg/docassembly/service/ServiceNameAspectTest.java
https://tools.hmcts.net/jira/browse/EM-4065
Resolve Error status with code : 500 for ServiceNameAspect
```
[ ] Yes
[X] No
```
=> Em 4065 resolve error status with code 500

build.gradle
https://tools.hmcts.net/jira/browse/EM-4113
Fix CVE-2021-22044
```
[ ] Yes
[X] No
```
=> Em 4113 resolve vulnerabilities

build.gradle, src/main/java/uk/gov/hmcts/reform/dg/docassembly/service/ServiceNameAspect.java
https://tools.hmcts.net/jira/browse/EM-4185
Updated sonar config
```
[ ] Yes
[X] No
```
=> Updated sonar config

src/main/java/uk/gov/hmcts/reform/dg/docassembly/conversion/DocmosisConverter.java, src/main/java/uk/gov/hmcts/reform/dg/docassembly/rest/DocumentConversionResource.java, src/main/java/uk/gov/hmcts/reform/dg/docassembly/service/DmStoreUploader.java, src/main/java/uk/gov/hmcts/reform/dg/docassembly/service/FormDefinitionService.java
https://tools.hmcts.net/jira/browse/EM-4185
Fix SonarQube issues
```
[ ] Yes
[X] No
```
=> Fix sonar issues

charts/dg-docassembly/Chart.yaml, charts/dg-docassembly/values.yaml
https://tools.hmcts.net/jira/browse/EM-4252
Whitelisted adoption_cos_api
```
[ ] Yes
[X] No
```
=> Whitelisted adoption_cos_api

build.gradle
https://tools.hmcts.net/jira/browse/EM-4264
Updated CVE fix to resolve TimeOuts on Prod. Just making sure both tomcat library are referring to same version.
```
[ ] Yes
[X] No
```
=> Updated CVE fix

charts/dg-docassembly/Chart.yaml
https://tools.hmcts.net/jira/browse/EM-4268
Update helm chart
```
[ ] Yes
[X] No
```
=> Update helm chart

config/owasp/dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/EM-4275
Removed suppression
```
[ ] Yes
[X] No
```
=> Removed suppression

database/Dockerfile
https://tools.hmcts.net/jira/browse/EM-4290
update postgres version to 11 for local setup
```
[ ] Yes
[X] No
```
=> update postgres version to 11 for local setup

charts/dg-docassembly/Chart.yaml
https://tools.hmcts.net/jira/browse/DTSSE-1141
```
[ ] Yes
[ ] No
```
=> docassembly java chart upgd. Update Chart.yaml

charts/dg-docassembly/Chart.yaml
bump java chart
```
[ ] Yes
[X] No
```
=> bump java chart

bin/start-local-environment.sh, build.gradle, config/owasp/dependency-check-suppressions.xml, docker-compose-dependencies.yml, idam-client-setup.sh, src/aat/resources/application.yml, src/main/java/uk/gov/hmcts/reform/dg/docassembly/Application.java, src/main/java/uk/gov/hmcts/reform/dg/docassembly/config/SwaggerConfiguration.java, src/main/java/uk/gov/hmcts/reform/dg/docassembly/config/security/SecurityConfiguration.java, src/main/java/uk/gov/hmcts/reform/dg/docassembly/rest/DocumentConversionResource.java, src/main/java/uk/gov/hmcts/reform/dg/docassembly/rest/FormDefinitionResource.java, src/main/java/uk/gov/hmcts/reform/dg/docassembly/rest/TemplateRenditionResource.java, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/EM-4298
Upgraded SpringBoot version to 2.6.4
```
[ ] Yes
[X] No
```
=> Upgraded SpringBoot version to 2.6.4

audit.json, security.sh
https://tools.hmcts.net/jira/browse/EM-4301
Fix security scan
```
[ ] Yes
[X] No
```
=> Fix security scan

audit.json
https://tools.hmcts.net/jira/browse/EM-4301
Nightly build Security Scan fix
```
[ ] Yes
[X] No
```
=> Nightly build Security Scan fix

build.gradle, config/owasp/dependency-check-suppressions.xml
=> fixed CVE-2022-26336 + CVE-2020-21913

src/main/java/uk/gov/hmcts/reform/dg/docassembly/service/impl/FileToPDFConverterServiceImpl.java
https://tools.hmcts.net/jira/browse/EM-4367
Updated file extension check to be case insensitive
```
[ ] Yes
[X] No
```
=> Updated file extension check

build.gradle
https://tools.hmcts.net/jira/browse/EM-4383
Check and update the exclusion list of Sonar Coverage Classes
```
[ ] Yes
[X] No
```
=> Em-4383 check sonar exclusions

src/aat/java/uk/gov/hmcts/reform/dg/docassembly/functional/SecureTemplateRenditionResourceTests.java, src/aat/java/uk/gov/hmcts/reform/dg/docassembly/functional/TemplateRenditionResourceTests.java, src/main/java/uk/gov/hmcts/reform/dg/docassembly/dto/TemplateIdDto.java, src/main/java/uk/gov/hmcts/reform/dg/docassembly/service/TemplateRenditionException.java
https://tools.hmcts.net/jira/browse/EM-4176
Updated Response code for template renditions
```
[ ] Yes
[X] No
```
=> Updated Response code for template renditions

README.md, src/main/java/uk/gov/hmcts/reform/dg/docassembly/config/SwaggerConfiguration.java, src/main/java/uk/gov/hmcts/reform/dg/docassembly/rest/DocumentConversionResource.java, src/main/java/uk/gov/hmcts/reform/dg/docassembly/rest/FormDefinitionResource.java, src/main/java/uk/gov/hmcts/reform/dg/docassembly/rest/TemplateRenditionResource.java
https://tools.hmcts.net/jira/browse/EM-4396
Updated Swagger doc
```
[ ] Yes
[X] No
```
=> Updated Swagger doc

src/main/java/uk/gov/hmcts/reform/dg/docassembly/conversion/DocmosisConverter.java, src/main/java/uk/gov/hmcts/reform/dg/docassembly/service/exception/DocumentProcessingException.java, src/test/java/uk/gov/hmcts/reform/dg/docassembly/conversion/DocmosisConverterTest.java
https://tools.hmcts.net/jira/browse/EM-4461
Updated the Response Error code
```
[ ] Yes
[X] No
```
=> Updated the Response Error code

bin/idam/idam.sh, bin/start-local-environment.sh, docker-compose-demo.yml, docker-compose-dependencies-simulator.yml, docker-compose-dependencies.yml, idam-client-setup.sh, src/aat/resources/application.yml, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/EM-4470
Updated local S2S & IDAM port
```
[ ] Yes
[X] No
```
=> Updated local S2S & IDAM port

build.gradle, settings.gradle, src/aat/java/uk/gov/hmcts/reform/dg/docassembly/functional/OpenIdConnectSceanarios.java, src/aat/resources/application.yml, src/cftlib/java/uk/gov/hmcts/reform/dg/docassembly/config/cftlib/CftLibConfig.java, src/main/resources/application.yaml, src/main/resources/cftlib-am-role-assignments.json
https://tools.hmcts.net/jira/browse/EM-4470
Added in changes for CFTlib
```
[ ] Yes
[X] No
```
=> Added in changes for CFTlib

src/aat/java/uk/gov/hmcts/reform/dg/docassembly/testutil/ExtendedCcdHelper.java
https://tools.hmcts.net/jira/browse/EM-4495
Removed redundant Ccd Def File import logic to resolve PR build failure.
```
[ ] Yes
[X] No
```
=> Removed redundant Ccd Def File import logic

src/main/java/uk/gov/hmcts/reform/dg/docassembly/service/ServiceNameAspect.java
https://tools.hmcts.net/jira/browse/EM-4560
Resolve service exception
```
[ ] Yes
[x] No
```
=> Resolve service exception

build.gradle
https://tools.hmcts.net/jira/browse/EM-4598
Fix issue with upgrading poi-ooxml
```
[ ] Yes
[x] No
```
=> Upgrade poi-ooxml

build.gradle
This reverts commit 05ba009c11f11d5ed44e695c0a71924184bfd735.
https://tools.hmcts.net/jira/browse/EM-4598
Revert previous change to fix fortify scan failure
```
[ ] Yes
[x] No
```
=> Revert "Upgrade poi-ooxml (#761)"

charts/dg-docassembly/Chart.yaml, charts/dg-docassembly/values.yaml, infrastructure/main.tf
EM-4606 copy app-insights-connection-string from rpa
=> EM-4606 copy app-insights-connection-string from rpa

src/main/java/uk/gov/hmcts/reform/dg/docassembly/service/CdamService.java
=> EM-4636 change log level

build.gradle
EM-4645 avoid - CVE-2022-42003
=> EM-4645 avoid - CVE-2022-42003

src/main/java/uk/gov/hmcts/reform/dg/docassembly/config/HttpClientConfiguration.java, src/main/resources/application.yaml
=> Em-4648 setup max connection

src/main/java/uk/gov/hmcts/reform/dg/docassembly/config/HttpClientConfiguration.java, src/main/java/uk/gov/hmcts/reform/dg/docassembly/service/DocmosisApiClient.java, src/main/java/uk/gov/hmcts/reform/dg/docassembly/service/DocmosisTimeoutException.java, src/main/java/uk/gov/hmcts/reform/dg/docassembly/service/TimeoutException.java, src/test/java/uk/gov/hmcts/reform/dg/docassembly/service/DocmosisApiClientTest.java
EM-4648 create custom exception
=> EM-4648 create custom exception

build.gradle
EM-4666 remove unnecessary log libs
https://tools.hmcts.net/jira/browse/EM-4666
```
[ ] Yes
[x] No
```
=> EM-4666 remove unnecessary log libs

build.gradle
https://tools.hmcts.net/jira/browse/EM-4719
bump auth-checker-lib to 2.1.5
```
[ ] Yes
[x] No
```
=> bump auth-checker-lib to 2.1.5

src/main/java/uk/gov/hmcts/reform/dg/docassembly/conversion/DocmosisConverter.java, src/main/java/uk/gov/hmcts/reform/dg/docassembly/service/DmStoreUploader.java, src/main/java/uk/gov/hmcts/reform/dg/docassembly/service/DocmosisApiClient.java, src/main/java/uk/gov/hmcts/reform/dg/docassembly/service/HttpOkResponseCloser.java, src/main/java/uk/gov/hmcts/reform/dg/docassembly/service/TemplateManagementApiClient.java, src/main/java/uk/gov/hmcts/reform/dg/docassembly/service/TemplateRenditionService.java, src/main/java/uk/gov/hmcts/reform/dg/docassembly/service/impl/DmStoreDownloaderImpl.java
[EM-4751](https://tools.hmcts.net/jira/browse/EM-4751) close http response
=> EM-4751 close http response

src/main/java/uk/gov/hmcts/reform/dg/docassembly/service/HttpOkResponseCloser.java
[EM-4790 ](https://tools.hmcts.net/jira/browse/EM-4790)check response before close
=> EM-4790 check response

config/owasp/dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/EM-5125
Updated CVE list for now, as the Base Score is Medium. Should be resolved as part of https://tools.hmcts.net/jira/browse/EM-5113
```
[ ] Yes
[X] No
```
=> Updated CVE list

Dockerfile, build.gradle
[https://tools.hmcts.net/jira/browse/EM-5170](url)
Resolve CVE-2023-28708
```
[ ] Yes
[x ] No
```
=> Updated Dependency

audit.json
Em-5186 suppress sec scan vulnerability-2
=> Em-5186 suppress sec scan vulnerability-2

src/aat/java/uk/gov/hmcts/reform/dg/docassembly/smoke/SmokeTest.java, src/main/java/uk/gov/hmcts/reform/dg/docassembly/rest/WelcomeResource.java, src/test/java/uk/gov/hmcts/reform/dg/docassembly/rest/WelcomeResourceTest.java
[https://tools.hmcts.net/jira/browse/EM-5193](url)
Welcome endpoint to return JSON response
```
[ ] Yes
[x] No
```
=> Em 5193 endpoint to return json

src/main/java/uk/gov/hmcts/reform/dg/docassembly/service/DocmosisApiClient.java
https://tools.hmcts.net/jira/browse/EM-5208
Added in more logs for Docmosis call
```
[ ] Yes
[X] No
```
=> Added in more logs

charts/dg-docassembly/values.preview.template.yaml
Em 5300 override app-insight access
=> Em 5300 override appinsight access

build.gradle, gradle/wrapper/gradle-wrapper.properties
https://tools.hmcts.net/jira/browse/EM-5339
upgrade to gradle 8
```
[ ] Yes
[x] No
```
=> upgrade to gradle 8

audit.json
https://tools.hmcts.net/jira/browse/EM-5485
added 1 fingerprint to audit.json
=> em-5485: added 1 fingerprint to audit.json

build.gradle, config/checkstyle/checkstyle.xml, src/main/java/uk/gov/hmcts/reform/dg/docassembly/config/security/SecurityConfiguration.java, src/main/java/uk/gov/hmcts/reform/dg/docassembly/service/DmStoreUploader.java, src/test/java/uk/gov/hmcts/reform/dg/docassembly/conversion/DocmosisConverterTest.java, src/test/java/uk/gov/hmcts/reform/dg/docassembly/rest/DocumentConversionResourceTest.java
[https://tools.hmcts.net/jira/browse/EM-5430](url)
Update Checkstyle
```
[ ] Yes
[x] No
```
=> Em 5430 update check style

.github/renovate.json, config/owasp/dependency-check-suppressions.xml
=> EM-5551 fix renovate config

lib/applicationinsights.json, src/main/java/uk/gov/hmcts/reform/dg/docassembly/conversion/DocmosisConverter.java, src/main/java/uk/gov/hmcts/reform/dg/docassembly/rest/DocumentConversionResource.java, src/main/java/uk/gov/hmcts/reform/dg/docassembly/service/DocmosisApiClient.java, src/main/java/uk/gov/hmcts/reform/dg/docassembly/service/impl/DmStoreDownloaderImpl.java, src/main/java/uk/gov/hmcts/reform/dg/docassembly/service/impl/FileToPDFConverterServiceImpl.java
EM-5505 reduce app-insight logs
=> EM-5505 reduce app-insight logs

src/main/java/uk/gov/hmcts/reform/dg/docassembly/service/impl/DmStoreDownloaderImpl.java
=> Em 5605 change log level to debug

src/main/java/uk/gov/hmcts/reform/dg/docassembly/service/impl/DmStoreDownloaderImpl.java, src/test/java/uk/gov/hmcts/reform/dg/docassembly/service/DmStoreDownloaderImplTest.java
=> Em-5605 remove logs fix

build.gradle, config/owasp/dependency-check-suppressions.xml
=> EM-5717 arrange gradle dependency management

build.gradle
=> EM-5715 fix pact test

src/main/java/uk/gov/hmcts/reform/dg/docassembly/config/security/SecurityConfiguration.java
https://tools.hmcts.net/jira/browse/EM-5805
update deprecated security config
=> update deprecated config

build.gradle, config/owasp/dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/EM-5851
update commons compress to resolve cve
=> resolve cve

charts/dg-docassembly/Chart.yaml
https://tools.hmcts.net/jira/browse/EM-5956
=> Upgrade java chart to 5.2.0

src/main/java/uk/gov/hmcts/reform/dg/docassembly/service/DmStoreUploader.java
https://tools.hmcts.net/jira/browse/EM-5921
=> fixed missed code smells

charts/dg-docassembly/Chart.yaml, charts/dg-docassembly/values.yaml
https://tools.hmcts.net/jira/browse/EM-5976
=> Enabling spot instances in lower envs

charts/dg-docassembly/Chart.yaml, charts/dg-docassembly/values.yaml
https://tools.hmcts.net/jira/browse/EM-5989
Disabled Spot instances.
=> Disabled Spot instances

src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/EM-6227
add env variable for application port
=> add env variable for application port

build.gradle
https://tools.hmcts.net/jira/browse/EM-6326
update package for okhttp mock
=> update package for okhttp mock

Jenkinsfile_CNP, build.gradle, src/contractTest/java/uk/gov/hmcts/reform/dg/docassembly/IdamConsumerTest.java
https://tools.hmcts.net/jira/browse/EM-6326
update pact to 4.6.5
=> Em 6326 update pact

build.gradle, src/aat/java/uk/gov/hmcts/reform/dg/docassembly/functional/BaseTest.java
https://tools.hmcts.net/jira/browse/EM-6385
upgrade em-test-helper to 2.1.1
add retry extension
=> upgrade em-test-helper to 2.1.1

charts/dg-docassembly/Chart.yaml
https://tools.hmcts.net/jira/browse/EM-6546
Upgrading chart to new OCI version, bumping to new minor version
=> EM-6546 Upgrading to oci charts

charts/dg-docassembly/Chart.yaml, charts/dg-docassembly/values.yaml
https://tools.hmcts.net/jira/browse/EM-6647
whitelisted PCS service for non-prod environments.
N/A
=> whitelisted PCS service

Jenkinsfile_CNP, build.gradle, src/contractTest/java/uk/gov/hmcts/reform/dg/docassembly/consumer/BaseConsumerTest.java, src/contractTest/java/uk/gov/hmcts/reform/dg/docassembly/consumer/DocumentConversionConsumerTest.java, src/contractTest/java/uk/gov/hmcts/reform/dg/docassembly/consumer/IdamConsumerTest.java, src/contractTest/java/uk/gov/hmcts/reform/dg/docassembly/provider/BaseProviderTest.java, src/contractTest/java/uk/gov/hmcts/reform/dg/docassembly/provider/ContractTestProviderConfiguration.java, src/contractTest/java/uk/gov/hmcts/reform/dg/docassembly/provider/DocumentConversionProviderTest.java
[6524
](https://tools.hmcts.net/jira/browse/EM-6524)
add pact test
=> add pact test
